package com.foodfun.common.model;

import com.foodfun.common.model.base.BaseClassify;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Classify extends BaseClassify<Classify> {
	public static final Classify dao = new Classify();
	
	public Page<Classify> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from classify");
	}
}
