package com.foodfun.common.model;

import com.foodfun.common.model.base.BaseFun;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Fun extends BaseFun<Fun> {
	public static final Fun dao = new Fun();
	
	public Page<Fun> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from fun");
	} 
}
