package com.foodfun.common.model;

import com.foodfun.common.model.base.BaseFuncollect;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Funcollect extends BaseFuncollect<Funcollect> {
	public static final Funcollect dao = new Funcollect();
	
	public Page<Funcollect> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from funcollect");
	}
}
