package com.foodfun.common.model;

import com.foodfun.common.model.base.BaseMclassify;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mclassify extends BaseMclassify<Mclassify> {
	public static final Mclassify dao = new Mclassify();
	
	public Page<Mclassify> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from mclassify order by mclassifyId asc");
	}
}
