package com.foodfun.common.model;

import com.foodfun.common.model.base.BaseOpenuser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Openuser extends BaseOpenuser<Openuser> {
	public static final Openuser dao = new Openuser();
}
