package com.foodfun.common.model;

import com.foodfun.common.model.base.BaseRecipes;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Recipes extends BaseRecipes<Recipes> {
	public static final Recipes dao = new Recipes();
	
	public Page<Recipes> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from recipes");
	}
}
