package com.foodfun.common.model;

import com.foodfun.common.model.base.BaseTest;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Test extends BaseTest<Test> {
	public static final Test me = new Test();
	
	public Page<Test> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from test order by id asc");
	}
}
