package com.foodfun.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFun<M extends BaseFun<M>> extends Model<M> implements IBean {

	public void setFunId(java.lang.Integer funId) {
		set("funId", funId);
	}

	public java.lang.Integer getFunId() {
		return get("funId");
	}

	public void setFunTitle(java.lang.String funTitle) {
		set("funTitle", funTitle);
	}

	public java.lang.String getFunTitle() {
		return get("funTitle");
	}

	public void setFunContent(java.lang.String funContent) {
		set("funContent", funContent);
	}

	public java.lang.String getFunContent() {
		return get("funContent");
	}

	public void setFunImage(java.lang.String funImage) {
		set("funImage", funImage);
	}

	public java.lang.String getFunImage() {
		return get("funImage");
	}

}
