package com.foodfun.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClassify<M extends BaseClassify<M>> extends Model<M> implements IBean {

	public void setClassifyId(java.lang.Integer classifyId) {
		set("classifyId", classifyId);
	}

	public java.lang.Integer getClassifyId() {
		return get("classifyId");
	}

	public void setClassifyName(java.lang.String classifyName) {
		set("classifyName", classifyName);
	}

	public java.lang.String getClassifyName() {
		return get("classifyName");
	}

	public void setClassifyImage(java.lang.String classifyImage) {
		set("classifyImage", classifyImage);
	}

	public java.lang.String getClassifyImage() {
		return get("classifyImage");
	}

	public void setFKclassifyId(java.lang.Integer FKclassifyId) {
		set("FKclassifyId", FKclassifyId);
	}

	public java.lang.Integer getFKclassifyId() {
		return get("FKclassifyId");
	}

}
