package com.foodfun.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setUserAccount(java.lang.String userAccount) {
		set("userAccount", userAccount);
	}

	public java.lang.String getUserAccount() {
		return get("userAccount");
	}

	public void setUserPassword(java.lang.String userPassword) {
		set("userPassword", userPassword);
	}

	public java.lang.String getUserPassword() {
		return get("userPassword");
	}

	public void setUserName(java.lang.String userName) {
		set("userName", userName);
	}

	public java.lang.String getUserName() {
		return get("userName");
	}

	public void setUserPost(java.lang.String userPost) {
		set("userPost", userPost);
	}

	public java.lang.String getUserPost() {
		return get("userPost");
	}

	public void setUserNum(java.lang.String userNum) {
		set("userNum", userNum);
	}

	public java.lang.String getUserNum() {
		return get("userNum");
	}

	public void setUserCollect(java.lang.Integer userCollect) {
		set("userCollect", userCollect);
	}

	public java.lang.Integer getUserCollect() {
		return get("userCollect");
	}

	public void setUserImage(java.lang.String userImage) {
		set("userImage", userImage);
	}

	public java.lang.String getUserImage() {
		return get("userImage");
	}

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

}
