package com.foodfun.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRecipes<M extends BaseRecipes<M>> extends Model<M> implements IBean {

	public void setRecipesId(java.lang.Integer recipesId) {
		set("recipesId", recipesId);
	}

	public java.lang.Integer getRecipesId() {
		return get("recipesId");
	}

	public void setRecipesName(java.lang.String recipesName) {
		set("recipesName", recipesName);
	}

	public java.lang.String getRecipesName() {
		return get("recipesName");
	}

	public void setRecipesMfood(java.lang.String recipesMfood) {
		set("recipesMfood", recipesMfood);
	}

	public java.lang.String getRecipesMfood() {
		return get("recipesMfood");
	}

	public void setRecipesFood(java.lang.String recipesFood) {
		set("recipesFood", recipesFood);
	}

	public java.lang.String getRecipesFood() {
		return get("recipesFood");
	}

	public void setRecipesLevel(java.lang.String recipesLevel) {
		set("recipesLevel", recipesLevel);
	}

	public java.lang.String getRecipesLevel() {
		return get("recipesLevel");
	}

	public void setRecipesIntro(java.lang.String recipesIntro) {
		set("recipesIntro", recipesIntro);
	}

	public java.lang.String getRecipesIntro() {
		return get("recipesIntro");
	}

	public void setRecipesTime(java.lang.String recipesTime) {
		set("recipesTime", recipesTime);
	}

	public java.lang.String getRecipesTime() {
		return get("recipesTime");
	}

	public void setRecipesStep(java.lang.String recipesStep) {
		set("recipesStep", recipesStep);
	}

	public java.lang.String getRecipesStep() {
		return get("recipesStep");
	}

	public void setRecipesCollect(java.lang.Integer recipesCollect) {
		set("recipesCollect", recipesCollect);
	}

	public java.lang.Integer getRecipesCollect() {
		return get("recipesCollect");
	}

	public void setFKrecipesEffect(java.lang.Integer FKrecipesEffect) {
		set("FKrecipesEffect", FKrecipesEffect);
	}

	public java.lang.Integer getFKrecipesEffect() {
		return get("FKrecipesEffect");
	}

	public void setFKrecipesTaste(java.lang.Integer FKrecipesTaste) {
		set("FKrecipesTaste", FKrecipesTaste);
	}

	public java.lang.Integer getFKrecipesTaste() {
		return get("FKrecipesTaste");
	}

	public void setFKrecipesType(java.lang.Integer FKrecipesType) {
		set("FKrecipesType", FKrecipesType);
	}

	public java.lang.Integer getFKrecipesType() {
		return get("FKrecipesType");
	}

	public void setRecipesImage(java.lang.String recipesImage) {
		set("recipesImage", recipesImage);
	}

	public java.lang.String getRecipesImage() {
		return get("recipesImage");
	}

	public void setRecipesEffect(java.lang.String recipesEffect) {
		set("recipesEffect", recipesEffect);
	}

	public java.lang.String getRecipesEffect() {
		return get("recipesEffect");
	}

}
