package com.foodfun.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCollect<M extends BaseCollect<M>> extends Model<M> implements IBean {

	public void setCollectId(java.lang.String collectId) {
		set("collectId", collectId);
	}

	public java.lang.String getCollectId() {
		return get("collectId");
	}

	public void setFKcollectUser(java.lang.Integer FKcollectUser) {
		set("FKcollectUser", FKcollectUser);
	}

	public java.lang.Integer getFKcollectUser() {
		return get("FKcollectUser");
	}

	public void setFKrecipesId(java.lang.String FKrecipesId) {
		set("FKrecipesId", FKrecipesId);
	}

	public java.lang.String getFKrecipesId() {
		return get("FKrecipesId");
	}

	public void setFKfunId(java.lang.String FKfunId) {
		set("FKfunId", FKfunId);
	}

	public java.lang.String getFKfunId() {
		return get("FKfunId");
	}

}
